# Generated by Django 4.2.4 on 2023-08-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0003_alter_userprofile_profilephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="userId",
            field=models.CharField(max_length=20),
        ),
    ]
