# Generated by Django 4.2.4 on 2023-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0006_alter_userprofile_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="userId",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
